#!/bin/bash

source /home/bitnami/.bashrc

cd /home/bitnami/apps/django/django_projects/avatar

git fetch
git reset --hard origin/master

source /opt/bitnami/python/.virtualenvs/avatar/bin/activate
pip install -r requirements.txt

cd portfolio/reactserver
npm install

cd /home/bitnami/apps/django/django_projects/avatar
python3 manage.py runprod