#!/bin/bash

PATH="$PATH:/opt/bitnami/nodejs/bin:/opt/bitnami/git/bin:/opt/bitnami/python/bin"

cd /home/bitnami/apps/django/django_projects/avatar

source .env

NODE_ENVS="NODE_HOST=$REACTSERVER_HOST NODE_PORT=$REACTSERVER_PORT NODE_ENV=production"

git fetch
git reset --hard origin/master

source /opt/bitnami/python/.virtualenvs/avatar/bin/activate
pip install -r requirements.txt

cd portfolio/reactserver
npm install
npm run build:client
npm run build:server
eval "$NODE_ENVS npm run start:server"
