# Generated by Django 3.0.4 on 2020-09-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_avataruser_server_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataruser',
            name='last_check',
            field=models.TextField(default='none', max_length=500),
        ),
    ]
