# Generated by Django 3.0.4 on 2020-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_avataruser_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataruser',
            name='last_check',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
