# Generated by Django 3.0.4 on 2020-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_profile_name', models.CharField(max_length=200)),
                ('classes', models.IntegerField()),
                ('class_types', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('classes_per_teacher', models.IntegerField()),
                ('students', models.IntegerField()),
            ],
        ),
    ]
