# Generated by Django 3.0.4 on 2020-04-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.UUIDField()),
                ('class_type', models.CharField(max_length=200)),
                ('database_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.DatabaseProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_id', models.UUIDField()),
                ('database_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.DatabaseProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.UUIDField()),
                ('classes', models.ManyToManyField(to='profiler.Class')),
                ('database_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.DatabaseProfile')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiler.Teacher'),
        ),
    ]
