# Generated by Django 3.0.4 on 2020-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_auto_20200417_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=200),
        ),
    ]
