# Generated by Django 3.0.4 on 2020-04-17 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0004_auto_20200417_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.RemoveField(
            model_name='databaseprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='databaseprofile',
            name='db_profile_id',
            field=models.CharField(default=uuid.UUID('86fd929f-6422-4dd3-b0d9-edbde31e9ffc'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default=uuid.UUID('06bd89d1-06c6-4d8e-a58c-0b827b1c812a'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=uuid.UUID('f4886d66-1881-4138-acae-3d503e47f8ea'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=uuid.UUID('77c58e51-3c40-488c-ab00-cfdf968e042b'), max_length=200, primary_key=True, serialize=False),
        ),
    ]
