# Generated by Django 3.0.4 on 2020-04-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0008_auto_20200418_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='database_profile',
            new_name='db_profile',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='database_profile',
            new_name='db_profile',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='databaseprofile',
            name='db_profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        )
    ]
