# Generated by Django 3.0.4 on 2020-04-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0009_auto_20200420_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='database_profile',
            new_name='db_profile',
        ),
    ]
