# Generated by Django 3.0.4 on 2020-04-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0011_revert_primary_key_bugfix'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseprofile',
            name='classes_per_student',
            field=models.IntegerField(default=1),
        ),
    ]
