# Generated by Django 3.0.4 on 2020-04-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0012_databaseprofile_classes_per_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseprofile',
            name='classes_per_student',
            field=models.IntegerField(),
        ),
    ]
