# Generated by Django 3.0.4 on 2020-05-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0013_auto_20200420_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseprofile',
            name='completion_progress',
            field=models.IntegerField(default=0),
        ),
    ]
