# Generated by Django 3.0.4 on 2020-04-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetails',
            options={'verbose_name': 'Project DetailsPage', 'verbose_name_plural': 'Project DetailsPage'},
        ),
    ]
