# Generated by Django 3.0.4 on 2020-04-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200405_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
