# Generated by Django 3.0.4 on 2020-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetails',
            options={'verbose_name': 'Project Details Page', 'verbose_name_plural': 'Project Details Page'},
        ),
    ]
